---
- name: Install Java
  dnf:
    name: java-21-amazon-corretto
    state: present

- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: start & enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: add ec2-user in jenkins group
  user:
    name: jenkins
    groups:
      - ec2-user
      - docker
    append: yes

- name: jenkins sudo privileges
  copy:
    dest: /etc/sudoers 
    mode: '0440'
    content: "jenkins ALL=(ALL:ALL) NOPASSWD: ALL"
