---
- name: Read join command from master
  delegate_to: "{{ groups['cicd'][0] }}"
  shell: cat /tmp/kube_join_command.sh
  register: join_cmd
  changed_when: false

- name: Join worker node
  become: true
  shell: "{{ join_cmd.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf