plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Project: cloudvault
  instance-state-name: running

hostnames:
  - private-ip-address

groups:
  cicd: tags.Name == 'cloudvault-cicd-server'
  web: tags.Name == 'cloudvault-web-server'
  app: tags.Name == 'cloudvault-app-server'

compose:
  ansible_host: private_ip_address