---
- name: Create ArgoCD namespace
  shell: |
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

- name: Install ArgoCD
  shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Expose ArgoCD server
  shell: |
    kubectl patch svc argocd-server -n argocd \
    -p '{"spec": {"type": "NodePort"}}'