---
- name: Copy join command from master
  fetch:
    src: /tmp/kube_join_command.sh
    dest: /tmp/kube_join_command.sh
    flat: yes

- name: Join worker node to cluster
  shell: sh /tmp/kube_join_command.sh