---
- name : install helm link
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: install helm
  shell: /tmp/get_helm.sh
