---
- name: Disable swap
  shell: swapoff -a

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'

- name: Add Kubernetes repository
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

- name: Install Kubernetes packages
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: all

- name: Enable kubelet
  service:
    name: kubelet
    enabled: true

- name: Start kubelet
  service:
    name: kubelet
    state: started