--- 
- name: install metrics server
  shell: | 
    kubectl apply -f  https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

- name: pathch metrics server
  shell: |
    kubectl patch deployment metrics- server -n kube-system --type='jsion' -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'
    