apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudvault-config
  namespace: cloudvault
data:
  DB_HOST: "cloudvault-db-rds-endpoint"
  DB_NAME: "cloudvaultdb"
  AWS_REGION: "ap-south-1"
  S3_BUCKET: "cloudvault-file-storage"