---
- name: Add Prometheus Helm repository
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Update Helm repositories
  shell: |
    helm repo update

- name: Install Prometheus stack
  shell: |
    helm install prometheus prometheus-community/kube-prometheus-stack