--- 
- name: update package 
  dnf:
    name: "*"
    state: latest

- name: install docker
  dnf:
    name: docker
    state: present

- name: start docker
  service: 
    name: docker
    state: started
    enabled: true

- name: add ec2 user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes