---
- name: Initialize Kubernetes Cluster with kubeadm
  shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address }}"
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for ec2-user
  file:
    path: /home/ec2-user/.kube
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Copy admin.conf to ec2-user kubeconfig location
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ec2-user/.kube/config
    remote_src: true
    owner: ec2-user
    group: ec2-user
    mode: "0600"

- name: Wait for Kubernetes API
  shell: kubectl get nodes
  environment:
    KUBECONFIG: /home/ec2-user/.kube/config
  register: api_ready
  retries: 30
  delay: 10
  until: api_ready.rc == 0
  changed_when: false

- name: Install Calico CNI
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/calico.yaml
  environment:
    KUBECONFIG: /home/ec2-user/.kube/config

- name: Generate worker join command
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Save join command
  set_fact:
    kube_join_cmd: "{{ join_command.stdout }}"

- name: Write join command to file
  copy:
    dest: /tmp/kube_join_command.sh
    content: "{{ kube_join_cmd }}"
    mode: "0755"